repos:
- hooks:
  - args:
    - --multi-line=3
    - --trailing-comma
    - --force-grid-wrap=0
    - --use-parentheses
    - --line-width=88
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - additional_dependencies:
    - flake8-eradicate==0.4.0
    args:
    - --max-line-length=89
    id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.1.0
- hooks:
  - args:
    - --ignore-missing-imports
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
- hooks:
  - args:
    - --convention=numpy
    - --add-ignore=D104
    id: pydocstyle
  repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
- hooks:
  - additional_dependencies:
    - black==20.8b1
    id: blacken-docs
  repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
- hooks:
  - exclude: ^docs/*
    id: trailing-whitespace
  - exclude: ^docs/*
    id: end-of-file-fixer
  - id: debug-statements
  - id: check-case-conflict
  - id: check-json
  - id: check-yaml
  - id: mixed-line-ending
  - id: check-toml
  - id: pretty-format-json
  - id: check-docstring-first
  - id: check-symlinks
  - id: detect-private-key
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.4
