[tool.poetry]
name = "subpulse"
version = "2021.05-alpha.0"
description = "CHIME/FRB Backend - subpulse"
authors = ["Shiny Brar <charanjotbrar@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.0"
maestro = {git = "ssh://git@github.com/CHIMEFRB/maestro.git", branch="main"}

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
mkdocs-material = "^5.5.3"
pre-commit = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
