# This workflow will build docker images for maestro
name: Subpulse Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-core:
    runs-on: ubuntu-latest
    steps:
    -
      name: configure git-commit-hash
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    -
      name: checkout code
      uses: actions/checkout@v2
    -
      name: setup ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      id: ssh-agent-setup
      with:
        ssh-private-key: ${{ secrets.FRB_BOT_SSH_ID }}
    -
      name: setup docker-buildx
      uses: docker/setup-buildx-action@v1
    -
      name: configure docker-login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: setup docker-cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-cache-${{ steps.slug.outputs.sha8 }}
        restore-keys: |
          ${{ runner.os }}-buildx-cache-
    -
      name: build subpulse
      uses: docker/build-push-action@v2
      id: subpulse
      with:
        context: .
        file: Dockerfile
        tags: |
          chimefrb/subpulse:latest
          chimefrb/subpulse:${{ steps.slug.outputs.sha8 }}
        ssh: "github_ssh_key=${{ steps.ssh-agent-setup.outputs.SSH_AUTH_SOCK}}"
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
